

1.   Numpy provides efficient storage
2.   It also provides ways of handling data for processing

3.   It is fast
4.   It is easy to learn

5.   Numpy uses relatively less memory to store data

6.   IMP for mathematical operation
7.   List 










It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are 6 general mechanisms for creating arrays:


1.   Conversion from other Python structures (i.e. lists and tuples)
2.   Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3.   Replicating, joining, or mutating existing arrays
4.   Reading arrays from disk, either from standard or custom formats

5.   Creating arrays from raw bytes through the use of strings or buffers
6.   Use of special library functions (e.g., random)

















In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,37,23]],np.int8)

In [3]:
myarr

array([[ 3,  4, 37, 23]], dtype=int8)

In [4]:
myarr[0,1]

4

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,1] = 10

In [8]:
myarr

array([[ 3, 10, 37, 23]], dtype=int8)

In [9]:
myarr[0,1] = 45

In [10]:
myarr

array([[ 3, 45, 37, 23]], dtype=int8)

**Array creation** :Conversion from other Python structures

In [11]:
listarray = np.array([[1,2,3],[5,6,7],[8,6,5]])


In [12]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 5]])

In [13]:
type(myarr)

numpy.ndarray

In [14]:
#an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. 
#Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
#the total number of elements of the array. This is equal to the product of the elements of shape.
listarray.size

9

In [17]:
np.array({34,43,56})

array({56, 34, 43}, dtype=object)

Intrinsic numpy array creation objects

In [18]:
zeros = np.zeros((2,3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [21]:
zeros.shape

(2, 3)

In [22]:
rng = np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,5,4)


In [25]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [26]:
emp = np.empty((4,6))

In [27]:
emp

array([[4.68864774e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [30]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [31]:
ide = np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
#the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. 
#For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
ide.shape

(45, 45)

In [34]:
arr = np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr = arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr = arr.ravel()

In [39]:
arr.shape

(99,)

**Numpy Axis**

2D - Axis0(Row),Axis1(Col)

1D - Axis0

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [45]:
#transpose
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [46]:
#itretor
ar.flat

In [47]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [48]:
#the number of axes (dimensions) of the array.
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

72

In [51]:
one = np.array([1,2,3,4,5,6])

In [52]:
one.argmax()

5

In [53]:
one.argmin()

0

In [54]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [57]:
ar.argmin()

8

In [58]:
ar.argmax()

6

In [59]:
ar.argmax(axis=0)

array([2, 1, 1])

In [60]:
ar.argmax(axis=1)

array([2, 2, 0])

In [61]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [62]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
#Return a contiguous flattened array.
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [66]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [70]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [72]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
ar.sum()

29

In [75]:
ar.max()

7

In [76]:
ar.min()

0

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [79]:
type(np.where(ar>5))

tuple

In [80]:
np.count_nonzero(ar)

8

In [81]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [82]:
ar[1,2] = 0

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [84]:
import sys

In [85]:
py_ar = [0,4,55,2]

In [86]:
np_ar = np.array(py_ar)

In [87]:
sys.getsizeof(1) * len(py_ar)

112

In [88]:
np_ar.itemsize * np_ar.size

32

In [89]:
np_ar.tolist()

[0, 4, 55, 2]